---
abstract: 'Integrate HTML::FormFu with DBIx::Class'
author:
  - 'Carl Franks'
build_requires:
  Test::MockObject: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-FormFu-Model-DBIC
no_index:
  directory:
    - inc
    - t
requires:
  DBD::SQLite: 0
  DBIx::Class: 0.08002
  DateTime::Format::MySQL: 0
  HTML::FormFu: 0.03000
  Task::Weaken: 0
  perl: 5.8.1
version: 0.03000
