---
abstract: 'Integrate HTML::FormFu with DBIx::Class'
author:
  - 'Carl Franks'
build_requires:
  DateTime::Format::SQLite: 0
  ExtUtils::MakeMaker: 6.42
  SQL::Translator: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu-Model-DBIC
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBD::SQLite: 0
  DBIx::Class: 0.08108
  HTML::FormFu: 0.09001
  List::MoreUtils: 0
  Task::Weaken: 0
  YAML::Syck: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/fireartist/HTML-FormFu-Model-DBIC.git
version: 0.09001
